export { applyAging } from "./aging";
export type { AgingResult } from "./aging";
export { tryGraduateYouth, youthMonthlyCost } from "./youth";
export type { YouthInvestment, YouthConfig, YouthGraduate } from "./youth";
export { checkRandomArrivals, performRecruitment } from "./recruitment";
export type { RecruitmentAction, RecruitmentResult, RandomArrival } from "./recruitment";
export { simulateTraining } from "./training";
export type { TrainingType, TrainingApproach, TrainingPlan, TrainingResult } from "./training";
export { generateSponsors, calculateMatchIncome, calculateMatchExpenses, calculateMonthlyBudget, calculateMatchReward, calculateSeasonReward, calculateTrainingCost, calculateRepairCost } from "./economy";
export type { Sponsor, MatchIncome, MatchDayExpenses, MonthlyBudget, MatchResultReward, SeasonReward } from "./economy";
export { generateNamingOffers, generateArenaOffers } from "./naming-rights";
export type { NamingType, NamingRightsOffer, ArenaRightsOffer } from "./naming-rights";
export { generateSeasonCalendar, getLineupDeadline } from "./calendar";
export type { CalendarEntry, SeasonCalendar } from "./calendar";
export { executeDailyTick } from "./daily-tick";
export type { DailyTickResult, DailyTickEvent } from "./daily-tick";
export { getSeasonalEventsForWeek, generateNewspaperArticle } from "./seasonal-events";
export type { SeasonalEventType, SeasonalEventDef } from "./seasonal-events";
