-- Manager attributes — FM-style coaching stats + bio
ALTER TABLE managers ADD COLUMN age INTEGER;
ALTER TABLE managers ADD COLUMN coaching INTEGER NOT NULL DEFAULT 40;
ALTER TABLE managers ADD COLUMN motivation INTEGER NOT NULL DEFAULT 40;
ALTER TABLE managers ADD COLUMN tactics INTEGER NOT NULL DEFAULT 40;
ALTER TABLE managers ADD COLUMN youth_development INTEGER NOT NULL DEFAULT 40;
ALTER TABLE managers ADD COLUMN discipline INTEGER NOT NULL DEFAULT 40;
ALTER TABLE managers ADD COLUMN reputation INTEGER NOT NULL DEFAULT 30;
ALTER TABLE managers ADD COLUMN bio TEXT;
