-- Okres České Budějovice: příjmení + doplnění obcí s fotbalovým klubem (sponzoři beze změny, viz 0216).
-- Idempotentní. Aplikovat ručně: npx wrangler d1 execute <db> --remote --file <tento soubor>
-- Zdroj příjmení: https://www.prijmeni.cz/oblast/3301-ceske_budejovice (ženské tvary vynechány)

-- Příjmení dle četnosti (prijmeni.cz, jen mužské tvary, 150 nejčastějších)
INSERT OR IGNORE INTO district_surnames (district, surname, frequency) VALUES
  ('České Budějovice', 'Dvořák', 627), ('České Budějovice', 'Novák', 587), ('České Budějovice', 'Novotný', 507),
  ('České Budějovice', 'Svoboda', 290), ('České Budějovice', 'Kadlec', 269), ('České Budějovice', 'Marek', 245),
  ('České Budějovice', 'Kolář', 236), ('České Budějovice', 'Zeman', 233), ('České Budějovice', 'Kučera', 224),
  ('České Budějovice', 'Němec', 221), ('České Budějovice', 'Šimek', 214), ('České Budějovice', 'Veselý', 208),
  ('České Budějovice', 'Soukup', 197), ('České Budějovice', 'Bláha', 196), ('České Budějovice', 'Pokorný', 188),
  ('České Budějovice', 'Černý', 187), ('České Budějovice', 'Růžička', 185), ('České Budějovice', 'Beneš', 185),
  ('České Budějovice', 'Tůma', 183), ('České Budějovice', 'Klimeš', 181), ('České Budějovice', 'Vávra', 175),
  ('České Budějovice', 'Krejčí', 175), ('České Budějovice', 'Šíma', 174), ('České Budějovice', 'Pešek', 174),
  ('České Budějovice', 'Mareš', 173), ('České Budějovice', 'Klíma', 173), ('České Budějovice', 'Bárta', 173),
  ('České Budějovice', 'Čížek', 169), ('České Budějovice', 'Valenta', 168), ('České Budějovice', 'Kubeš', 167),
  ('České Budějovice', 'Vaněk', 165), ('České Budějovice', 'Kříž', 165), ('České Budějovice', 'Procházka', 164),
  ('České Budějovice', 'Jindra', 158), ('České Budějovice', 'Brož', 154), ('České Budějovice', 'Hájek', 151),
  ('České Budějovice', 'Mikeš', 146), ('České Budějovice', 'Švec', 144), ('České Budějovice', 'Sýkora', 144),
  ('České Budějovice', 'Říha', 144), ('České Budějovice', 'Vlček', 139), ('České Budějovice', 'Trnka', 138),
  ('České Budějovice', 'Mašek', 136), ('České Budějovice', 'Kouba', 135), ('České Budějovice', 'Blažek', 135),
  ('České Budějovice', 'Král', 129), ('České Budějovice', 'Tesař', 128), ('České Budějovice', 'Šesták', 125),
  ('České Budějovice', 'Janda', 125), ('České Budějovice', 'Hovorka', 125), ('České Budějovice', 'Pouzar', 123),
  ('České Budějovice', 'Dolejší', 122), ('České Budějovice', 'Matoušek', 121), ('České Budějovice', 'Urban', 119),
  ('České Budějovice', 'Turek', 118), ('České Budějovice', 'Horák', 117), ('České Budějovice', 'Doležal', 117),
  ('České Budějovice', 'Šindelář', 113), ('České Budějovice', 'Liška', 113), ('České Budějovice', 'Filip', 110),
  ('České Budějovice', 'Vácha', 109), ('České Budějovice', 'Fiala', 108), ('České Budějovice', 'Havel', 106),
  ('České Budějovice', 'Mach', 104), ('České Budějovice', 'Strnad', 103), ('České Budějovice', 'Matějka', 102),
  ('České Budějovice', 'Hajný', 102), ('České Budějovice', 'Staněk', 101), ('České Budějovice', 'Prokeš', 101),
  ('České Budějovice', 'Mráz', 101), ('České Budějovice', 'Sládek', 100), ('České Budějovice', 'Fencl', 100),
  ('České Budějovice', 'Hlaváč', 99), ('České Budějovice', 'Dušek', 98), ('České Budějovice', 'Hořejší', 97),
  ('České Budějovice', 'Moravec', 96), ('České Budějovice', 'Hruška', 96), ('České Budějovice', 'Beran', 95),
  ('České Budějovice', 'Leština', 94), ('České Budějovice', 'Šťastný', 93), ('České Budějovice', 'Holub', 93),
  ('České Budějovice', 'Petr', 92), ('České Budějovice', 'Pavlík', 92), ('České Budějovice', 'Jelínek', 92),
  ('České Budějovice', 'Jaroš', 92), ('České Budějovice', 'Kovář', 90), ('České Budějovice', 'Borovka', 90),
  ('České Budějovice', 'Čermák', 87), ('České Budějovice', 'Bednář', 87), ('České Budějovice', 'Kohout', 86),
  ('České Budějovice', 'Zíka', 84), ('České Budějovice', 'Vlk', 84), ('České Budějovice', 'Vacek', 84),
  ('České Budějovice', 'Štěpánek', 84), ('České Budějovice', 'Polák', 84), ('České Budějovice', 'Kratochvíl', 84),
  ('České Budějovice', 'Čapek', 83), ('České Budějovice', 'Bauer', 83), ('České Budějovice', 'Musil', 82),
  ('České Budějovice', 'Sedláček', 80), ('České Budějovice', 'Peterka', 80), ('České Budějovice', 'Brom', 80),
  ('České Budějovice', 'Beránek', 80), ('České Budějovice', 'Benda', 80), ('České Budějovice', 'David', 79),
  ('České Budějovice', 'Šmíd', 78), ('České Budějovice', 'Čech', 78), ('České Budějovice', 'Prokop', 77),
  ('České Budějovice', 'Nováček', 77), ('České Budějovice', 'Havlíček', 77), ('České Budějovice', 'Dubský', 76),
  ('České Budějovice', 'Ambrož', 76), ('České Budějovice', 'Kovařík', 75), ('České Budějovice', 'Ježek', 75),
  ('České Budějovice', 'Hála', 75), ('České Budějovice', 'Toman', 74), ('České Budějovice', 'Pražák', 74),
  ('České Budějovice', 'Bílek', 74), ('České Budějovice', 'Suchý', 73), ('České Budějovice', 'Pavlíček', 73),
  ('České Budějovice', 'Brabec', 72), ('České Budějovice', 'Klabouch', 71), ('České Budějovice', 'Holý', 71),
  ('České Budějovice', 'Postl', 70), ('České Budějovice', 'Janeček', 70), ('České Budějovice', 'Hrubý', 70),
  ('České Budějovice', 'Houška', 70), ('České Budějovice', 'Bartoš', 70), ('České Budějovice', 'Němeček', 69),
  ('České Budějovice', 'Michal', 69), ('České Budějovice', 'Kubíček', 69), ('České Budějovice', 'Pícha', 68),
  ('České Budějovice', 'Malý', 68), ('České Budějovice', 'Volf', 67), ('České Budějovice', 'Šedivý', 67),
  ('České Budějovice', 'Šafář', 67), ('České Budějovice', 'Macháček', 67), ('České Budějovice', 'Lexa', 67),
  ('České Budějovice', 'Kaňka', 67), ('České Budějovice', 'Kalina', 67), ('České Budějovice', 'Jílek', 67),
  ('České Budějovice', 'Diviš', 67), ('České Budějovice', 'Švehla', 66), ('České Budějovice', 'Stejskal', 66),
  ('České Budějovice', 'Míka', 66), ('České Budějovice', 'Majer', 66), ('České Budějovice', 'Fišer', 66),
  ('České Budějovice', 'Boček', 66), ('České Budějovice', 'Vlášek', 65), ('České Budějovice', 'Vaněček', 65);

-- ═══ Obce s fotbalovým oddílem (OFS ČB / I.A, I.B třída), 14 nových → celkem 30 ═══
-- Homole = TJ Slovan Černý Dub (hřiště v Nových Homolích). Populace a souřadnice: Wikidata (ČSÚ).
INSERT OR IGNORE INTO villages (id, name, district, region, population, size, lat, lng) VALUES
('cb-nove-hrady', 'Nové Hrady', 'České Budějovice', 'Jihočeský kraj', 2469, 'village', 48.7897, 14.7784),
('cb-zabovresky', 'Žabovřesky', 'České Budějovice', 'Jihočeský kraj', 443, 'hamlet', 49.0029, 14.3349),
('cb-dobra-voda-u-ceskych-budejovic', 'Dobrá Voda u Českých Budějovic', 'České Budějovice', 'Jihočeský kraj', 2652, 'village', 48.9683, 14.5249),
('cb-borek', 'Borek', 'České Budějovice', 'Jihočeský kraj', 1585, 'village', 49.0235, 14.5009),
('cb-rimov', 'Římov', 'České Budějovice', 'Jihočeský kraj', 1025, 'village', 48.8557, 14.4868),
('cb-usilne', 'Úsilné', 'České Budějovice', 'Jihočeský kraj', 487, 'hamlet', 49.0135, 14.5073),
('cb-jankov', 'Jankov', 'České Budějovice', 'Jihočeský kraj', 391, 'hamlet', 48.9665, 14.2979),
('cb-homole', 'Homole', 'České Budějovice', 'Jihočeský kraj', 1685, 'village', 48.9390, 14.4295),
('cb-divcice', 'Dívčice', 'České Budějovice', 'Jihočeský kraj', 626, 'hamlet', 49.1087, 14.3093),
('cb-horni-stropnice', 'Horní Stropnice', 'České Budějovice', 'Jihočeský kraj', 1492, 'village', 48.7613, 14.7350),
('cb-kamenny-ujezd', 'Kamenný Újezd', 'České Budějovice', 'Jihočeský kraj', 2694, 'village', 48.8976, 14.4464),
('cb-borsov-nad-vltavou', 'Boršov nad Vltavou', 'České Budějovice', 'Jihočeský kraj', 2105, 'village', 48.9219, 14.4340),
('cb-sevetin', 'Ševětín', 'České Budějovice', 'Jihočeský kraj', 1367, 'village', 49.1001, 14.5722),
('cb-neplachov', 'Neplachov', 'České Budějovice', 'Jihočeský kraj', 367, 'hamlet', 49.1304, 14.6010);
