-- Update news body (remove new manager mention) + notify 13 human teams
-- Generated: 2026-05-14T22:46:21.720Z

UPDATE news SET body = 'Vedení SK Čkyně se po měsících apatického vedení rozhodlo udělat tlustou čáru: Master Blaster (37, bývalý hráč, poslední dobou převážně bývalý) má padáka. Posledního tréninku se zúčastnilo 12 z 20 chlapů — zbytek sekal trávu do noci, vyklízel stodolu po dědovi, byl na nočce nebo si prostě "myslel, že je trénink zítra". "Když to nebere vážně kouč, proč bysme my?" uvedl pro Hospodský Zpravodaj anonymní záložník.

Master Blaster údajně naposledy dorazil na hřiště před třemi týdny, a to jen aby zkontroloval, zda hospoda U Pumpy ještě stojí. Tu šanci využil důkladně. Klub mu poděkoval za jeho slavnou hráčskou minulost a popřál mu hodně štěstí v dalším angažmá — pokud možno daleko od Čkyně.' WHERE id = '110125a7-13cd-4462-b97b-93778088ae53';

INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('990b0fc8-5e88-48ce-ab17-678bf33fd51c', '587c0b31-b463-44cc-bde9-ef60c9690382', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = '587c0b31-b463-44cc-bde9-ef60c9690382';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('b4760051-8e25-4137-ae48-f3b69d69a97c', '81c8a422-1dde-4845-bb8a-cd6fec7f9a47', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = '81c8a422-1dde-4845-bb8a-cd6fec7f9a47';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('cba53b65-a9d8-46ce-9e5f-e370428bb43e', '1b02f8c6-72c4-4bf9-8953-5b93c89928cb', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = '1b02f8c6-72c4-4bf9-8953-5b93c89928cb';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('7aee0506-9387-4321-ac38-9af4bd024d31', '19557cb0-a5ef-4d09-91bc-b2ace9b68876', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = '19557cb0-a5ef-4d09-91bc-b2ace9b68876';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('a73a3014-f95a-4cfe-adc7-9da571331ad2', 'e8ed119b-b81c-4a29-ac6e-db6c3ccd4774', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 'e8ed119b-b81c-4a29-ac6e-db6c3ccd4774';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('2816e89e-d6bb-4570-8475-2c58b2e454b8', 'b880fa00-698d-49af-9c7a-d2889d968c12', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 'b880fa00-698d-49af-9c7a-d2889d968c12';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('c3954bd8-f00c-48cf-8aa1-fff95cb1721b', 'dd141ec7-077b-46f7-af0a-87d763943287', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 'dd141ec7-077b-46f7-af0a-87d763943287';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('70fc8811-7414-4f4f-9653-1aeff791a4a0', 'be7ee63b-ea94-4241-86b2-4913c2e8e57e', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 'be7ee63b-ea94-4241-86b2-4913c2e8e57e';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('3d808d53-f4c8-4c6a-b90c-6655f9176412', 'ef70805c-447d-472a-a544-e9806f0730e6', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 'ef70805c-447d-472a-a544-e9806f0730e6';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('b8569f9b-9b04-4995-8440-533b9a1a4500', 'd08249f2-396a-44f3-a202-4cf5a969e472', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 'd08249f2-396a-44f3-a202-4cf5a969e472';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('6c8fcc2f-cfeb-4567-9510-aa1dea86a279', '766d11ad-79b3-44e1-b9f3-87c4aa2485a3', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = '766d11ad-79b3-44e1-b9f3-87c4aa2485a3';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('57bef664-08a4-411e-b23d-69d654371b4b', 'a1bf06da-610c-40f8-831e-04a50b492c39', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 'a1bf06da-610c-40f8-831e-04a50b492c39';
INSERT INTO messages (id, conversation_id, sender_type, sender_name, body, sent_at) VALUES ('0f9af754-bd3b-4b01-8412-92bbe679b931', '5ebc680b-0a9a-43c2-887d-6260f563fdfe', 'system', 'Redakce Zpravodaje', '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, kdy je trénink"', strftime('%Y-%m-%dT%H:%M:%SZ', 'now'));
UPDATE conversations SET unread_count = unread_count + 1, last_message_text = '📰 Vyšel nový článek ve Zpravodaji: „Master Blaster vyhozen — Čkyně hledá kouče, který si pamatuje, ', last_message_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = '5ebc680b-0a9a-43c2-887d-6260f563fdfe';
