// Okresy pro žádost o personalizaci; nezávislé na tom, zda už mají herní data.
export const REGISTRATION_DISTRICTS = [
  "Benešov",
  "Beroun",
  "Blansko",
  "Brno-město",
  "Brno-venkov",
  "Bruntál",
  "Břeclav",
  "Česká Lípa",
  "České Budějovice",
  "Český Krumlov",
  "Děčín",
  "Domažlice",
  "Frýdek-Místek",
  "Havlíčkův Brod",
  "Hodonín",
  "Hradec Králové",
  "Cheb",
  "Chomutov",
  "Chrudim",
  "Jablonec nad Nisou",
  "Jeseník",
  "Jičín",
  "Jihlava",
  "Jindřichův Hradec",
  "Karlovy Vary",
  "Karviná",
  "Kladno",
  "Klatovy",
  "Kolín",
  "Kroměříž",
  "Kutná Hora",
  "Liberec",
  "Litoměřice",
  "Louny",
  "Mělník",
  "Mladá Boleslav",
  "Most",
  "Náchod",
  "Nový Jičín",
  "Nymburk",
  "Olomouc",
  "Opava",
  "Ostrava-město",
  "Pardubice",
  "Pelhřimov",
  "Písek",
  "Plzeň-jih",
  "Plzeň-město",
  "Plzeň-sever",
  "Praha",
  "Praha-východ",
  "Praha-západ",
  "Prachatice",
  "Prostějov",
  "Přerov",
  "Příbram",
  "Rakovník",
  "Rokycany",
  "Rychnov nad Kněžnou",
  "Semily",
  "Sokolov",
  "Strakonice",
  "Svitavy",
  "Šumperk",
  "Tábor",
  "Tachov",
  "Teplice",
  "Trutnov",
  "Třebíč",
  "Uherské Hradiště",
  "Ústí nad Labem",
  "Ústí nad Orlicí",
  "Vsetín",
  "Vyškov",
  "Zlín",
  "Znojmo",
  "Žďár nad Sázavou"
] as const;

export interface RegistrationDistrict {
  name: string;
  status: "available" | "preparing" | "ready";
}
